# **NumPy**

NumPy (Numerical Python) is a Python library for fast numerical computing. It provides a powerful N-dimensional array (ndarray) and many mathematical operations that are much faster than Python lists.

# **1. Install NumPy**

In [ ]:
pip install numpy

pip install numpy

In [2]:
import numpy as np

In [2]:
#check Version
print(np.__version__)

2.0.2


# **2. Create Arrays**

In [3]:
#1D Array
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [4]:
#2D Array
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
#3D Array
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


# **3. Array Properties**

In [14]:
arr = np.array([[1,2.5,3.5],[4.4,5.5,6.5]])

print(arr.ndim)


2


In [15]:
print(arr.shape)

(2, 3)


In [16]:
print(arr.size)

6


In [17]:
print(arr.dtype)


float64


In [18]:
print(arr.itemsize)

8


# **4. Creating Special Arrays**

In [19]:
#Zeros
print(np.zeros((5,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [20]:
#Ones
print(np.ones((2,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
#Identity Matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
#Full 
print(np.full((3,3),100))

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [23]:
#Random Integer
print(np.random.randint(1,100,(4,4)))

[[96 37 99  2]
 [43 38 85 52]
 [82 75 54 55]
 [19 38 59 78]]


# **5. Sequence Arrays**

In [24]:
print(np.arange(1,20))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [25]:
print(np.arange(0,20,3))

[ 0  3  6  9 12 15 18]


# **6. Reshape**

In [3]:
arr=np.arange(12)

print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
#Flatten
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# **7. Indexing**

In [8]:
#1D
arr=np.array([10,20,30,40])

print(arr[0])
print(arr[-1])

10
40


In [10]:
#2D
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(arr[0,1])
print(arr[1,2])

2
6


# **8. Slicing**

In [16]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
print(arr[2:7])
print(arr[:5])
print(arr[5:])

[2 3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]


In [ ]:
arr=np.arange(10)

print(arr[2:7])
print(arr[:5])
print(arr[5:])

# **9. Mathematical Operations**

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

# **10. Aggregate Functions**

In [ ]:
import numpy as np

In [ ]:
arr=np.array([10,20,30,40])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))

# **11. Axis Operations**

In [2]:
import numpy as np

In [4]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.sum(axis=0))

[5 7 9]


In [5]:
print(arr.sum(axis=1))

[ 6 15]


# **12. Matrix Operations**

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

print(A+B)
print(A-B)
print(A*B)

In [ ]:
#Matrix Multiplication
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


print(np.dot(A,B))


In [ ]:
#or
print(np.dot(A,B))
#Transpose
print(A.T)
#Inverse
print(np.linalg.inv(A))
#Determinant
print(np.linalg.det(A))

# **13. Random Module**

In [ ]:
np.random.seed(1)

print(np.random.rand(50))

In [ ]:
#Normal Distribution
print(np.random.randn(5))

In [ ]:
#choice
print(np.random.choice([10,20,30],4))

In [ ]:
#Shuffle
arr=np.arange(50)

np.random.shuffle(arr)

print(arr)

# **14. Boolean Indexing**

In [ ]:
arr=np.array([10,20,30,40,50])

print(arr[arr>25])

# **15. Where**

In [ ]:
arr=np.array([10,20,30,40])

print(np.where(arr>20))

In [ ]:
#Replace
arr=np.array([10,20,30,40])

print(np.where(arr>20))

# **16. Sorting**

In [ ]:
arr=np.array([5,2,9,1])

print(np.sort(arr))

# **17. Unique Values**

In [ ]:
arr=np.array([1,2,2,3,3,4])

print(np.unique(arr))

# **18. Concatenate**

In [ ]:
a=np.array([1,2])
b=np.array([3,4])

print(np.concatenate((a,b)))

In [ ]:
#Vertical
A=np.array([[1,2]])
B=np.array([[3,4]])

print(np.vstack((A,B)))

In [ ]:
#Horizontal
print(np.hstack((A,B)))

# **19. Split**

In [ ]:
arr=np.arange(8)

print(np.split(arr,4))

# **20. Broadcasting**


In [ ]:
arr=np.array([1,2,3])

print(arr+10)

In [ ]:
#2D
A=np.array([[1],[2],[3]])
B=np.array([10,20,30])

print(A+B)

# **21. Copy vs View**

In [ ]:
arr=np.array([1,2,3])

view=arr.view()

copy=arr.copy()

arr[0]=100

print(view)
print(copy)

# **22. Masking**

In [ ]:
arr=np.arange(20)

mask=arr%2==0

print(arr[mask])

# **23. File Handling**

In [ ]:
arr=np.arange(10)

np.save("data.npy",arr)

In [ ]:
#load
data=np.load("data.npy")

print(data)

In [ ]:
#CSV
np.savetxt("data.csv",arr,delimiter=",")

In [ ]:
#Load CSV
data=np.loadtxt("data.csv",delimiter=",")

print(data)

# **24. Linear Algebra**
Eigen Values

In [ ]:
A=np.array([[4,2],[1,3]])

values,vectors=np.linalg.eig(A)

print(values)
print(vectors)

# **25. Statistics**

In [ ]:
arr=np.array([1,2,3,4,5])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.percentile(arr,50))

# **26. Universal Functions (ufunc)**

In [ ]:
arr=np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.square(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))

# **27. Advanced Indexing**

In [ ]:
arr=np.arange(20)

print(arr[[2,4,6]])

In [ ]:
#Fancy Indexing
arr=np.array([
    [1,2],
    [3,4],
    [5,6]
])

print(arr[[0,2]])

# **28. Broadcasting Example**

In [ ]:
A=np.ones((3,3))

B=np.array([1,2,3])

print(A+B)

# **29. Performance Comparison**

In [ ]:
import numpy as np
import time

x=list(range(1000000))
y=list(range(1000000))

start=time.time()

z=[x[i]+y[i] for i in range(len(x))]

print(time.time()-start)

a=np.arange(1000000)
b=np.arange(1000000)

start=time.time()

c=a+b

print(time.time()-start)

# **30. Real Example**

In [ ]:
marks=np.array([80,70,90,85,60])

print("Average:",marks.mean())
print("Highest:",marks.max())
print("Lowest:",marks.min())

passed=marks>=40

print("Passed Students:",marks[passed])