# **NumPy**

NumPy (Numerical Python) is a Python library for fast numerical computing. It provides a powerful N-dimensional array (ndarray) and many mathematical operations that are much faster than Python lists.

# **1. Install NumPy**

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 1.4 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


pip install numpy

In [4]:
import numpy as np

In [5]:
#check Version
print(np.__version__)

2.0.2


# **2. Create Arrays**

In [6]:
#1D Array
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [7]:
#2D Array
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D Array
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(arr)

# **3. Array Properties**

In [8]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.ndim)


2


In [9]:
print(arr.shape)

(2, 3)


In [10]:
print(arr.size)

6


In [11]:
print(arr.dtype)


int64


In [12]:
print(arr.itemsize)

8


# **4. Creating Special Arrays**

In [16]:
#Zeros
print(np.zeros((5,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
#Ones
print(np.ones((2,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
#Identity Matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
#Full 
print(np.full((3,3),100))

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [21]:
#Random Integer
print(np.random.randint(1,100,(4,4)))

[[ 5 54 19 53]
 [97  1 17  3]
 [95 81 20 20]
 [64 11 15 43]]


# **5. Sequence Arrays**

In [22]:
print(np.arange(1,20))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(np.arange(0,20,3))

[ 0  3  6  9 12 15 18]


# **6. Reshape**

In [25]:
arr=np.arange(12)

print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#Flatten
print(arr.reshape(3,4).flatten())

# **7. Indexing**

In [ ]:
#1D
arr=np.array([10,20,30,40])

print(arr[0])
print(arr[-1])

In [ ]:
#2D
arr=np.array([[1,2,3],[4,5,6]])

print(arr[0,1])
print(arr[1,2])

# **8. Slicing**

In [ ]:
arr=np.arange(10)

print(arr[2:7])
print(arr[:5])
print(arr[5:])

In [ ]:
arr=np.arange(10)

print(arr[2:7])
print(arr[:5])
print(arr[5:])

# **9. Mathematical Operations**

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

# **10. Aggregate Functions**

In [2]:
import numpy as np

In [3]:
arr=np.array([10,20,30,40])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))

100
25.0
40
10
11.180339887498949
125.0


# **11. Axis Operations**

In [4]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.sum(axis=0))
print(arr.sum(axis=1))

[5 7 9]
[ 6 15]


# **12. Matrix Operations**

In [5]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

print(A+B)
print(A-B)
print(A*B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [8]:
#Matrix Multiplication
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


print(np.dot(A,B))


[[19 22]
 [43 50]]


In [ ]:
#or
print(np.dot(A,B))
#Transpose
print(A.T)
#Inverse
print(np.linalg.inv(A))
#Determinant
print(np.linalg.det(A))

# **13. Random Module**

In [12]:
np.random.seed(1)

print(np.random.rand(50))

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01
 2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01
 4.17304802e-01 5.58689828e-01 1.40386939e-01 1.98101489e-01
 8.00744569e-01 9.68261576e-01 3.13424178e-01 6.92322616e-01
 8.76389152e-01 8.94606664e-01 8.50442114e-02 3.90547832e-02
 1.69830420e-01 8.78142503e-01 9.83468338e-02 4.21107625e-01
 9.57889530e-01 5.33165285e-01 6.91877114e-01 3.15515631e-01
 6.86500928e-01 8.34625672e-01 1.82882773e-02 7.50144315e-01
 9.88861089e-01 7.48165654e-01 2.80443992e-01 7.89279328e-01
 1.03226007e-01 4.47893526e-01 9.08595503e-01 2.93614148e-01
 2.87775339e-01 1.30028572e-01]


In [10]:
#Normal Distribution
print(np.random.randn(5))

[-0.66437971 -0.60555494 -0.65099088  0.51256776  0.26238882]


In [15]:
#choice
print(np.random.choice([10,20,30],4))

[30 10 10 20]


In [19]:
#Shuffle
arr=np.arange(50)

np.random.shuffle(arr)

print(arr)

[37 48 47 16 36 39 27 43 41 11 22  5 10 23 12 20  4 21 49  9 30 14 17 35
 44  8 18 26  0 19 46 34  2 29 15 28  3 13  7 31  1  6 33 40 32 25 42 38
 24 45]


# **14. Boolean Indexing**

In [20]:
arr=np.array([10,20,30,40,50])

print(arr[arr>25])

[30 40 50]


# **15. Where**

In [21]:
arr=np.array([10,20,30,40])

print(np.where(arr>20))

(array([2, 3]),)


In [22]:
#Replace
arr=np.array([10,20,30,40])

print(np.where(arr>20))

(array([2, 3]),)


# **16. Sorting**

In [23]:
arr=np.array([5,2,9,1])

print(np.sort(arr))

[1 2 5 9]


# **17. Unique Values**

In [24]:
arr=np.array([1,2,2,3,3,4])

print(np.unique(arr))

[1 2 3 4]


# **18. Concatenate**

In [26]:
a=np.array([1,2])
b=np.array([3,4])

print(np.concatenate((a,b)))

[1 2 3 4]


In [28]:
#Vertical
A=np.array([[1,2]])
B=np.array([[3,4]])

print(np.vstack((A,B)))

[[1 2]
 [3 4]]


In [29]:
#Horizontal
print(np.hstack((A,B)))

[[1 2 3 4]]


# **19. Split**

In [25]:
arr=np.arange(8)

print(np.split(arr,4))

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]


# **20. Broadcasting**


In [ ]:
arr=np.array([1,2,3])

print(arr+10)

In [ ]:
#2D
A=np.array([[1],[2],[3]])
B=np.array([10,20,30])

print(A+B)

# **21. Copy vs View**

In [ ]:
arr=np.array([1,2,3])

view=arr.view()

copy=arr.copy()

arr[0]=100

print(view)
print(copy)

# **22. Masking**

In [ ]:
arr=np.arange(20)

mask=arr%2==0

print(arr[mask])

# **23. File Handling**

In [ ]:
arr=np.arange(10)

np.save("data.npy",arr)

In [ ]:
#load
data=np.load("data.npy")

print(data)

In [ ]:
#CSV
np.savetxt("data.csv",arr,delimiter=",")

In [ ]:
#Load CSV
data=np.loadtxt("data.csv",delimiter=",")

print(data)

# **24. Linear Algebra**
Eigen Values

In [ ]:
A=np.array([[4,2],[1,3]])

values,vectors=np.linalg.eig(A)

print(values)
print(vectors)

# **25. Statistics**

In [ ]:
arr=np.array([1,2,3,4,5])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.percentile(arr,50))

# **26. Universal Functions (ufunc)**

In [ ]:
arr=np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.square(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))

# **27. Advanced Indexing**

In [ ]:
arr=np.arange(20)

print(arr[[2,4,6]])

In [ ]:
#Fancy Indexing
arr=np.array([
    [1,2],
    [3,4],
    [5,6]
])

print(arr[[0,2]])

# **28. Broadcasting Example**

In [ ]:
A=np.ones((3,3))

B=np.array([1,2,3])

print(A+B)

# **29. Performance Comparison**

In [ ]:
import numpy as np
import time

x=list(range(1000000))
y=list(range(1000000))

start=time.time()

z=[x[i]+y[i] for i in range(len(x))]

print(time.time()-start)

a=np.arange(1000000)
b=np.arange(1000000)

start=time.time()

c=a+b

print(time.time()-start)

# **30. Real Example**

In [ ]:
marks=np.array([80,70,90,85,60])

print("Average:",marks.mean())
print("Highest:",marks.max())
print("Lowest:",marks.min())

passed=marks>=40

print("Passed Students:",marks[passed])